print("Un café. El lugar está casi vacío, ya que parecen ser más de las 10 de la noche. Una joven trabaja en una mesa del lugar con un café casi vacío al lado.")
print("Un mesero se acerca a ella.")
print("Mesero: Buenas noches. ¿Va a querer algo más?")
print("Chica: Oh, no gracias. Ya casi termino esto.")
print("Mesero: Bien, entonces, si me permite...")
print("recoge la taza de café ya vacía de la mesa.")
print("Chica: No he podido trabajar en la oficina hoy. Ayer llovió tanto que se inundó gran parte del edificio y los cimientos se han resentido.")
print("Mesero: Eso llevará algo de tiempo con las reparaciones.")
print("Chica: Sí, así es.")
print("Mesero: Por esta parte de la ciudad no llovió tanto, pero el edificio en el que yo vivo estuvo bajo el agua, al menos hasta las escaleras de acceso a la primera planta. Menos mal, nadie salió herido.")
print("Chica: Con lo frecuentes que están siendo estas lluvias, tengo algunos amigos que creen que los impuestos subirán para poder pagar todas estas reparaciones.")
print("Mesero: No me extrañaría. A pesar de haber muchas propiedades privadas con edificios inundados, el estado también es dueño de muchas de las plazas comerciales que se están inundando, sin contar los edificios estatales.")
print("Chica: Con mi trabajo consigo ganar lo suficiente para pagar un poco más, no creo tener muchos problemas.")
print("Mesero: Eso es un alivio. Agradezco a quien sea que esté ahí arriba por darme un puesto de mesero en una cafetería tan prestigiosa. La paga no está nada mal.")
print("Chica: Si sigues hablando así, dejaré mi trabajo para trabajar aquí.")
print("El mesero se ríe mientras termina de retirar las cosas de la mesa. Mientras tanto, la chica guarda sus cosas en una mochila que hay a su derecha.")
print("Chica: Bien, gracias por todo. Buena charla, pero tengo que volver a casa.")
print("Mesero: Buenas noches, y vuelva pronto!")
