print("¿Cómo barrer una habitación?")
print("Primero tenemos que tomar la escoba y el recogedor.")
print("Tomamos el recogedor con la mano menos ágil, y buscamos la escoba. Esta tiene que ser una buena escoba, ya que hay algunas que no recogen casi nada de polvo.")
print("La escoba se toma con la mano que tenga más destreza y agilidad, y nos acercamos a la habitación en cuestión.")
print("Es recomendable dividir esta habitación en cuadrantes para evitar confusiones y para más efectividad.")
print("Dependiendo del espacio de la habitación serán más o menos cuadrantes.")
print("Ya con nuestra habitación dividida en cuadrantes, pasamos por cada uno realizando barridos con la escoba de la siguiente forma:")
print("Acercamos la escoba a unos 50 centímetros de nuestro cuerpo hacia adelante o hacia el costado, dependiendo hacia dónde queremos barrer. En ese momento, realizamos un movimiento contrario a la dirección en la que apuntan las cerdas de la escoba. Al hacer este movimiento y llegar a una distancia contraria de otros 40 centímetros, entra en juego el recogedor.")
print("Tomamos el recogedor y lo colocamos a 10 centímetros de la escoba. En ese momento, comenzamos a realizar pequeñas versiones del movimiento anteriormente explicado para la escoba, para que toda la basura que hayamos recogido se introduzca en el recogedor.")
print("Repetimos esta serie de movimientos siguiendo nuestros cuadrantes para que el suelo de la habitación quede totalmente limpio. Hay que evitar que el recogedor pierda toda la basura que tenía, así que tenemos que colocarlo de forma diagonal al suelo con la parte más delgada hacia arriba para evitar que la basura y el polvo regresen al suelo.")
print("Entonces, al terminar, tomamos la escoba y el recogedor, los levantamos con cuidado de no volver a manchar el suelo, y sacudimos la escoba en el basurero abierto para retirar los excedentes de polvo.")
print("Luego la colocamos en su lugar, y repetimos la misma acción con el recogedor.")
print("¡Y así barremos una habitación! Espero que esta información te haya sido útil.")
print("No olviden barrer todas las habitaciones de sus casas una vez por semana, al menos para tener todo limpio y presentable.")
